### ISSUE TITLE
gpuRcuda doesn't compile on mac os x 10.10 / R 3.2.2 / CUDA 7.0

### ISSUE THREAD

**Issue by newffy** [gpuRcore/gpuRcuda#1]
Hello again!
I've tried to install gpuRcuda and got compilation error.
Here is installation log:

```
> devtools::install_github("cdeterman/gpuRcuda")
Downloading github repo cdeterman/gpuRcuda@master
Installing gpuRcuda
Skipping 2 packages not available: gpuR, RViennaCL
'/usr/local/Cellar/r/3.2.2_1/R.framework/Resources/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore CMD INSTALL  \
  '/private/var/folders/_q/zp_t57xd69sdc_zmc7rjn8qc0000gn/T/Rtmp8FblOg/devtools10b36309e0f9/cdeterman-gpuRcuda-1efc193'  \
  --library='/Users/newf/Library/R/3.2/library' --install-tests 

* installing *source* package ‘gpuRcuda’ ...
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
Checking for C++ Compiler
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++ accepts -g... (cached) yes
checking "Checking environment variable CUDA_HOME"... "using CUDA_HOME=/usr/local/cuda"
checking for /usr/local/cuda/bin/nvcc... yes
"NVCC found"
checking "whether this is the 64 bit linux version of CUDA"... checking for /usr/local/cuda/lib64/libcudart.so... no
"no -- using /usr/local/cuda/lib for CUDA libs"
checking for Rscript... yes
checking "building the nvcc command line"... configure: Building Makevars
configure: creating ./config.status
config.status: creating src/Makevars
** libs
/usr/local/cuda/bin/nvcc -arch=sm_30 -Xcompiler -fPIC -Xcudafe --diag_suppress=boolean_controlling_expr_is_constant -I/usr/local/Cellar/r/3.2.2_1/R.framework/Resources/include -I/Users/newf/Library/R/3.2/library/Rcpp/include -I"/Users/newf/Library/R/3.2/library/RcppEigen/include" -I/Users/newf/Library/R/3.2/library/RViennaCL/include vcl_daxpy.cu -c
/Users/newf/Library/R/3.2/library/RcppEigen/include/Eigen/src/Core/arch/SSE/PacketMath.h(560): error: argument of type "__v16qi" is incompatible with parameter of type "__attribute((vector_size(16))) long long"

/Users/newf/Library/R/3.2/library/RcppEigen/include/Eigen/src/Core/arch/SSE/PacketMath.h(560): error: argument of type "__v16qi" is incompatible with parameter of type "__attribute((vector_size(16))) long long"

/Users/newf/Library/R/3.2/library/RcppEigen/include/Eigen/src/Core/arch/SSE/PacketMath.h(570): error: argument of type "__v16qi" is incompatible with parameter of type "__attribute((vector_size(16))) long long"

/Users/newf/Library/R/3.2/library/RcppEigen/include/Eigen/src/Core/arch/SSE/PacketMath.h(570): error: argument of type "__v16qi" is incompatible with parameter of type "__attribute((vector_size(16))) long long"

/Users/newf/Library/R/3.2/library/RcppEigen/include/Eigen/src/Core/arch/SSE/PacketMath.h(580): error: argument of type "__v16qi" is incompatible with parameter of type "__attribute((vector_size(16))) long long"

/Users/newf/Library/R/3.2/library/RcppEigen/include/Eigen/src/Core/arch/SSE/PacketMath.h(580): error: argument of type "__v16qi" is incompatible with parameter of type "__attribute((vector_size(16))) long long"

6 errors detected in the compilation of "/var/folders/_q/zp_t57xd69sdc_zmc7rjn8qc0000gn/T//tmpxft_0000129f_00000000-5_vcl_daxpy.cpp4.ii".
make: *** [vcl_daxpy.o] Error 2
ERROR: compilation failed for package ‘gpuRcuda’
```

**Comment by cdeterman** [comment]
Thank you for trying this package on a Mac as well.  This actually doesn't surprise me.  The compilation behind this package is much more complex than `gpuR`.  It looks like you do have CUDA and NVCC installed so that certainly is a big hurdle you already passed.  I haven't tried compiling it with a 32 bit version and perhaps that is causing the problem but I'm not sure at the moment.  I want to finish my development on `gpuR` before I continue developing this companion package.  It doesn't have nearly as much functionality at the moment but once I have a stable version of `gpuR` I will devote more focus to this package but I simply don't have the time for both at the moment.

**Comment by newffy** [comment]
Thanks for clarifications!

2015-09-04 15:50 GMT+03:00 Charles Determan notifications@github.com:
